#!/bin/bash -e

HERE=`dirname ${0}`
cd "${HERE}"
cd ..
PROJECT=`pwd`
SINK="/tmp/build_quackery"

#cleanup
rm \
  --recursive \
  --force \
  ${SINK}

#compile
mkdir \
  --parents \
  ${SINK}
javac \
  -classpath "./main/jar/junit-4.12.jar:./main/jar/hamcrest-all-1.3.jar" \
  -sourcepath "./main/java" \
  -source 1.8 \
  -target 1.8 \
  -d "${SINK}" \
  ./main/java/org/quackery/Build.java

#copy sources
cp \
  --recursive \
  ./main/java/. \
  ${SINK}

#zip jar
cd ${SINK}
zip \
  --quiet \
  --recurse-paths \
  ./quackery.jar \
  ./*
cd "${PROJECT}"

echo ""
echo "BUILD SUCCESSFUL"
echo "created ${SINK}/quackery.jar"

#cleanup
rm \
  --recursive \
  --force \
  ${SINK}/*/
