#!/bin/bash -e

HERE=`dirname ${0}`
cd "${HERE}"
cd ..
PROJECT=`pwd`
SINK="./.sink"

#cleanup
rm \
  --recursive \
  --force \
  ${SINK}

#compile
mkdir \
  --parents \
  ${SINK}
javac \
  -classpath "./main/jar/junit-4.12.jar:./main/jar/hamcrest-all-1.3.jar:./test/jar/guava-18.0.jar" \
  -sourcepath "./main/java:./test/java" \
  -source 1.7 \
  -target 1.7 \
  -d "${SINK}" \
  ./main/java/org/quackery/Build.java \
  ./test/java/org/quackery/test_all.java

java \
  -classpath "${SINK}:./main/jar/junit-4.12.jar:./main/jar/hamcrest-all-1.3.jar:./test/jar/guava-18.0.jar" \
  org.quackery.test_all

#cleanup
rm \
  --recursive \
  --force \
  ${SINK}
